name: task_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_local_notifications: ^17.2.1+2
  flutter_timezone: ^2.1.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  time_machine: ^0.9.17
  timezone: ^0.9.4
  firebase_core: ^2.24.2
  firebase_ui_auth: ^1.13.0
  firebase_auth: ^4.20.0
  iconsax: ^0.0.8
  cloud_firestore: ^4.17.5
  intl: ^0.19.0
  sleek_circular_slider: ^2.0.1
  flex_color_picker: ^3.5.1
  gap: ^3.0.1
  bottom_picker: ^2.8.0
  shared_preferences: ^2.3.2
  table_calendar: ^3.1.2
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  flutter_displaymode: ^0.6.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter_native_splash:
  color: "#000000"
  android_12:
    color: "#000000"
  image: "assets/icons/icon.png"

