// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhuyWmyByEaaHG8oIKlzaKIyHRyRHeER4',
    appId: '1:192065838853:web:9715d6a58fe072bd1ae16c',
    messagingSenderId: '192065838853',
    projectId: 'taskmanager-6f957',
    authDomain: 'taskmanager-6f957.firebaseapp.com',
    storageBucket: 'taskmanager-6f957.appspot.com',
    measurementId: 'G-NSG78N9NND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJGCvhQKAP_rTdCitfQikC0svUR9oSmZo',
    appId: '1:192065838853:android:66d88371370c40101ae16c',
    messagingSenderId: '192065838853',
    projectId: 'taskmanager-6f957',
    storageBucket: 'taskmanager-6f957.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnSEyRAoc2K49WuIZ8VVBQNVM7NkN6EEU',
    appId: '1:192065838853:ios:ed6a44388c6812271ae16c',
    messagingSenderId: '192065838853',
    projectId: 'taskmanager-6f957',
    storageBucket: 'taskmanager-6f957.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnSEyRAoc2K49WuIZ8VVBQNVM7NkN6EEU',
    appId: '1:192065838853:ios:ed6a44388c6812271ae16c',
    messagingSenderId: '192065838853',
    projectId: 'taskmanager-6f957',
    storageBucket: 'taskmanager-6f957.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhuyWmyByEaaHG8oIKlzaKIyHRyRHeER4',
    appId: '1:192065838853:web:b0429b69cb58dba41ae16c',
    messagingSenderId: '192065838853',
    projectId: 'taskmanager-6f957',
    authDomain: 'taskmanager-6f957.firebaseapp.com',
    storageBucket: 'taskmanager-6f957.appspot.com',
    measurementId: 'G-V3XEHM29EH',
  );
}
